### PR TITLE
feat: use pyppeteer to scrape own data

### PR DESCRIPTION
**Pull request by laszukdawid**
### Changes

Somehow based on https://github.com/emcniece/bchydro/pull/25. Although `pyppeteer` is discouraged and Python3.8 is soon to be outdated, things "seems to work".

Contributing with this PR as is. Not sure if you want to upgrade a few things here and there. Since I'm going to update on my side to latest security patches might need to do a bit of refactoring.

### Test

Execute `python test_api_simple.py` with credentials in env variable.

As I don't have chrome/chromioum, I needed to pass local exec path for testing. Not sure if it works without passing the path directly. (I never worked with pyppeteer before :( )

### CODE REVIEW

**Comment by laszukdawid** [comment]
Seems that build is failing because credentials haven't been used in a year and BCHydro disabled(?) the user. Unfortunately, can't solve that :(

**Comment by emcniece** [comment]
Well I sure can! Lemme see if I can reactivate my account, why tf is it disabled... money on failed login attempts 😂

**Comment by emcniece** [comment]
Thank you so much for this work by the way. This is awesome.

**Comment by laszukdawid** [comment]
Weeellll.... dear unknown from the internet, you started it and saved me a bit of searching and poking. The least I can do is to give back a little.

I also asked BC Hydro whether they have API or plans to do it. Not sure if you seen it but they're "pushing" for usage of "HydroHome by BC Hydro" app ([google play link](https://play.google.com/store/apps/details?id=com.powerley.hydrohome&pli=1)). For some price they provide hub and analytics so doubt they'll just expose API. But, fingers crossed.

I'm starting work on home dashboard, so, time for scraping ;-)

**Comment by emcniece** [comment]
Thank you for reaching out and for your contributions, your news is honestly relieving.

The last time I tried to contact the company about their lack of API I was met with dead ends, everywhere: public contact forms, linkedin, github, phone, even internal referrals to dev team managers. 4 years ago I was told that an API was coming, but it wasn't public and there was no timeline and no official confirmation of this feature.

This repo represents dozens of hours of testing and troubleshooting and ultimately failure to produce a working product. After they implemented a captcha I gave up on this project, frustrated beyond belief. 

I haven't seen this app yet, I can't be sure the auth renewal will be sufficient for apps like this and Home Assistant, but maybe it will be. Hoping we don't have to 2FA every few days just to view our data.

**Comment by laszukdawid** [comment]
Hey @emcniece, this is my last update in this feature. Will now work on own fork. Got a few updates line up. Please let me know if want some updates in the future :)

**Comment by emcniece** [comment]
```sh
➜ python test_api_simple.py
INFO:pyppeteer.launcher:Browser listening on: ws://127.0.0.1:52625/devtools/browser/6e534490-387f-4928-8472-aad2c0635f82
{'2024-09-05': {'Event': '', 'Date': '2024-09-05', 'Tier 2 avg': '22.19', 'Total kWh': '34.39'}, '2024-09-06': {'Event': '', 'Date': '2024-09-06', 'Tier 2 avg': '22.19', 'Total kWh': '36.91'}, '2024-09-07': {'Event': '', 'Date': '2024-09-07', 'Tier 2 avg': '22.19', 'Total kWh': '30.17'}, '2024-09-08': {'Event': 'Start of Tier 2', 'Date': '2024-09-08', 'Tier 2 avg': '22.19', 'Total kWh': '32.74'}, '2024-09-09': {'Event': '', 'Date': '2024-09-09', 'Tier 2 avg': '22.19', 'Total kWh': '32.59'}, '2024-09-10': {'Event': '', 'Date': '2024-09-10', 'Tier 2 avg': '22.19', 'Total kWh': '26.43'}, '2024-09-11': {'Event': '', 'Date': '2024-09-11', 'Tier 2 avg': '22.19', 'Total kWh': '25.47'}}
INFO:pyppeteer.launcher:terminate chrome process...
```

It works! I'll keep playing with the Actions, looked like I got it working in https://github.com/emcniece/bchydro/pull/27 but it's still failing here for some reason.

I'd be happy to accept PRs in the future if you feel like it 😁 thank you for the help!

**Comment by laszukdawid** [comment]
Nice! :)

As for future PRs, might not be able to. Started refactoring a bit ... and got carried away, and removed almost all code to start from scratch :( The only "usable" file is the one submitted here but with the twist... that yesterday I actually migrated things to Playwright. Feel free to copy-paste it here if you prefer: https://github.com/laszukdawid/bchydro/blob/main/bchydro/scrapper.py

From the little work with Playwright, it's much nicer than pyppeteer. (For one, I can actually spell it correctly on the first attempt.) Main advantage is that one no longer needs to wait for each selector (although, I needed), and there's a nice graphical debugger (set via env variable `PWDEBUG=1` https://playwright.dev/python/docs/debug).

**Pull request merged**
